# Generated by Django 2.0.7 on 2018-08-13 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True, null=True)),
                ('page', models.CharField(blank=True, max_length=127, null=True)),
                ('element', models.CharField(blank=True, max_length=127, null=True)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('Alert', 'Alert'), ('Warning', 'Warning'), ('Info', 'Info'), ('Success', 'Success')], default='Alert', max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('active', models.BooleanField(default=True)),
                ('sent', models.BooleanField(default=False)),
                ('action_text', models.CharField(blank=True, max_length=255, null=True)),
                ('action_url', models.CharField(blank=True, max_length=511, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True, verbose_name='sent time')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='read time')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evacuation.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('place_id', models.CharField(blank=True, max_length=31, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
