# Generated by Django 2.0.7 on 2018-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0002_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Alert', 'Alert'), ('Warning', 'Warning'), ('Info', 'Info')], default='Alert', max_length=20),
        ),
    ]
