# Generated by Django 2.0.7 on 2018-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0003_auto_20180801_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
