# Generated by Django 2.0.7 on 2018-08-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0005_auto_20180821_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuser',
            name='phone_make',
            field=models.CharField(blank=True, choices=[('Iphone', 'Iphone'), ('Android', 'Android'), ('Other', 'Other')], max_length=15, null=True),
        ),
    ]
