# Generated by Django 2.0.7 on 2018-08-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0005_auto_20180801_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
