# Generated by Django 2.0.7 on 2018-08-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0006_notification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
