# Generated by Django 2.0.7 on 2018-08-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0006_evacuser_phone_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
    ]
