# Generated by Django 2.0.7 on 2018-08-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0007_auto_20180805_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Alert', 'Alert'), ('Warning', 'Warning'), ('Info', 'Info'), ('Success', 'Success')], default='Alert', max_length=15),
        ),
    ]
