# Generated by Django 2.0.7 on 2018-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0007_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='floor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
