# Generated by Django 2.0.7 on 2018-08-05 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0008_auto_20180805_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 2, 49, 30, 364386, tzinfo=utc), verbose_name='date sent'),
            preserve_default=False,
        ),
    ]
