# Generated by Django 2.0.7 on 2018-08-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0009_auto_20180805_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Message',
        ),
    ]
