# Generated by Django 2.0.7 on 2018-08-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evacuation', '0010_auto_20180805_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(verbose_name='sent time')),
                ('read_time', models.DateTimeField(verbose_name='read time')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evacuation.Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
