# Generated by Django 2.0.7 on 2018-08-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0012_message_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='group',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='person',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='read time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='sent time'),
        ),
    ]
