# Generated by Django 2.0.7 on 2018-08-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0013_auto_20180805_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
