# Generated by Django 2.0.7 on 2018-09-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0013_auto_20180918_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='floor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
