# Generated by Django 2.0.7 on 2018-09-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0014_office_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuser',
            name='desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evacuation.Desk'),
        ),
        migrations.AddField(
            model_name='evacuser',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evacuation.Office'),
        ),
    ]
