# Generated by Django 2.0.7 on 2018-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0015_auto_20180918_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('display_name', models.CharField(blank=True, max_length=63, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('floor', models.PositiveIntegerField()),
                ('icon', models.CharField(blank=True, max_length=63, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_landmark', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
