# Generated by Django 2.0.7 on 2018-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0015_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=31, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
