# Generated by Django 2.0.7 on 2018-08-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0016_obstacle'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacle',
            name='name',
            field=models.CharField(default='Obstacle', max_length=63),
            preserve_default=False,
        ),
    ]
