# Generated by Django 2.0.7 on 2018-09-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0016_auto_20180920_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuser',
            name='should_reload',
            field=models.BooleanField(default=False),
        ),
    ]
