# Generated by Django 2.0.7 on 2018-08-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('SingleChoice', 'SingleChoice')], default='Text', max_length=31),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.ChoiceGroup'),
        ),
    ]
