# Generated by Django 2.0.7 on 2018-09-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('survey', '0004_survey_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='group',
        ),
        migrations.AddField(
            model_name='survey',
            name='group_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_features', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='survey',
            name='group_landmarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_landmarks', to='auth.Group'),
        ),
    ]
