# Generated by Django 2.0.7 on 2018-09-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180907_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('SingleChoice', 'SingleChoice'), ('SingleChoiceOther', 'SingleChoiceOther'), ('MultipleChoice', 'MultipleChoice'), ('MultipleChoiceOther', 'MultipleChoiceOther'), ('Sketch', 'Sketch')], default='Text', max_length=31),
        ),
    ]
