# Generated by Django 2.0.7 on 2018-09-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_question_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='depends_on_text',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
